### ISSUE TITLE
Pruebas de Carga y Seguridad

### ISSUE THREAD

**Issue by a52290451** [udistrital/gestor_documental_mid#12]
Solicitar con anticipación las pruebas de carga y seguridad correspondientes al desarrollo realizado en el API gestor_documental_mid.

**Criterio de aceptación**

- [x] Documento con los resultados de las pruebas aplicadas.

**Nota:**

El documento resultado de las pruebas es entregado por parte del equipo de seguridad.
Se debe registrar en este ISSUE la realización de los ajustes solicitados en el documento resultado.

**Comment by a52290451** [comment]
Se realiza solicitud de pruebas de carga y seguridad a Maria Fernanda Avendaño el 01 de Octubre de 2021. Queda pendiente una respuesta al respecto.

**Comment by criss201x** [comment]
Se inicia desarrollo de ajustes necesarios para la api de acuerdo a los resultados de las pruebas de carga y seguridad, se realizara un commit por cada ajuste en la rama release, posterior a ello se deberán validar dichos ajustes por parte de @a52290451 y @mafeave para su posterior pr en rama master, se adjuntan documentos de resultados de pruebas de carga y seguridad. 

- [Evaluación de vulnerabilidades/Código fuentegestor_documental_mid](https://docs.google.com/document/d/1p_AcJRuCh1ywfVuD_5K1tdwn9c-t5zaL-CKPw6-8alQ/edit)
- [pruebas carga y seguridad gestor_documental_mid](https://docs.google.com/document/d/1CZPgZFZtbOlT3Lz7P3Rf4OSygIe7m2Xv-LVnAL6BVZc/edit)

**Comment by criss201x** [comment]
De acuerdo a las pruebas de carga y seguridad se da solución a la entrada de la petición de subida de documento a Nuxeo que venia definida como un array json, ahora permitiendo la subida de multiples documentos en la misma peticion, esta funcionalidad es opcional y no afecta en los diferentes clientes que usan el servicio

- cuerpo de la petición para múltiples documentos 
![Captura de pantalla de 2022-01-12 19-43-54](https://user-images.githubusercontent.com/57843585/149247820-71cf78c5-6812-493e-abcf-9035c351ba13.png)
- formato de respuesta para petición de subida de múltiples documentos 
![Captura de pantalla de 2022-01-12 19-43-18](https://user-images.githubusercontent.com/57843585/149247889-c55dc43f-d9d2-41a1-8f61-67056d9c845d.png)

**Comment by criss201x** [comment]
Se realizan correcciones a pruebas de carga y seguridad satisfactoriamente, dichas novedades pueden verse como problema vs solución en el siguiente documento 

- [Documento de correcciones a pruebas de carga y seguridad](https://docs.google.com/document/d/1wlyx0ovXQCYUhiyrgH6sVSN3ctjJ2OBurMvh1ORoG24/edit?usp=sharing)
