### ISSUE TITLE
Despliegue en ambiente de producción

### ISSUE THREAD

**Issue by a52290451** [udistrital/gestor_documental_mid#14]
Registrar la trazabilidad del despliegue del API gestor_documental_mid en ambiente de producción.

**Criterios de aceptación**

- [x] Commit en rama master del desarrollo consolidado y ajustado en rama release.

**Comment by criss201x** [comment]
Se actualiza checklist de requisitos técnicos para solicitud de despliegue del gestor documental mid en ambiente de producción 

- [Link del listado de requisitos técnicos para despliegue de apis (formato oficial)](https://docs.google.com/document/d/1Z8n1rp2aAFwbMUycoEdglT3E6PndrpJz/edit?usp=sharing&ouid=110288693142592643207&rtpof=true&sd=true)

**Comment by criss201x** [comment]
Se realizan correcciones necesarias para el paso del api a producción, se adjunta solicitud de despliegue en tuleap

- [Link solicitud en tuleap](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=44839)
- [Solicitud cambio de variables de entorno](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=44887)

**Comment by a52290451** [comment]
Se valida despliegue del gestor_documental_mid en ambiente de producción.
