### ISSUE TITLE
Pruebas funcionales y de usabilidad API gestor_documental_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/gestor_documental_mid#20]
Se debe realizar la planeación y ejecución de pruebas funcionales y de usabilidad relacionadas con el desarrollo del API gestor_documental_mid.

**Criterio de aceptación**

- [x] Documento que registre las pruebas funcionales y de usabilidad realizadas.

**Nota:** utilizar el [formato](https://docs.google.com/spreadsheets/d/1oymdKw9XVShKKk71AWzqUjPW-N26OdlRR_IB34X8Acs/edit?usp=sharing) dispuesto para la aplicación de este tipo de pruebas.

**Comment by criss201x** [comment]
Se realizan pruebas del gestor_documental_mid sobre [cumplidos_cliente ](https://github.com/udistrital/cumplidos_cliente/tree/develop) donde se evidencia el adecuado funcionamiento del mid, sin embargo en los resultados de las pruebas se deben considerar algunas correcciones menores, se adjunta documento de pruebas funcionales y de usabilidad 

- [Link del documento](https://docs.google.com/spreadsheets/d/1iKCcHDW7ZeLftR2d3yPrJaMJfkx4MIx4/edit?usp=sharing&ouid=110288693142592643207&rtpof=true&sd=true)

**Comment by a52290451** [comment]
Se validan pruebas funcionales realizadas. Para continuar con el proceso, se debe realizar la corrección de errores encontrados teniendo en cuenta las siguientes indicaciones:

1. Para la actualización en BD de los WorkSpaces, se requiere Script con los cambios necesarios para ejecución por parte de los DBAs.
2. En el caso de la funcionalidad relacionada con no permitir archivos duplicados, se debe deshabilitar temporalmente y no eliminar.
3. Para la funcionalidad requerida asociada a la eliminación de documentos, se debe implementar de tal forma que no afecte la transversalidad del API con otros sistemas.

**Comment by criss201x** [comment]
Se adjunta Script sql con los cambios necesarios para corregir los WorkSpaces en base de datos que no coinciden con los de Nuxeo: 
- [Link del Script.sql](https://drive.google.com/file/d/15XoEt2BT9fWZejY-bCEIxaAUWWjJor-Q/view?usp=sharing)

**Comment by criss201x** [comment]
Se realizan pruebas funcionales y de usabilidad sobre las correcciones realizadas en el gestor documental mid en el cliente de cumplidos, se ajunta segunda version del documento de pruebas funcionales

- [Link del documento versión 2.0](https://docs.google.com/spreadsheets/d/1Lenwfo9BoUqU3DIyS6zpSbhAhIU6lDjU/edit?usp=sharing&ouid=110288693142592643207&rtpof=true&sd=true)

**Comment by a52290451** [comment]
Se validan correcciones realizadas y se dan por terminadas las pruebas funcionales.
