### ISSUE TITLE
Pruebas unitarias para el API gestor_documental_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/gestor_documental_mid#22]
Implementar pruebas unitarias y refactor si es necesario, relacionadas con el API gestor_documental_mid.

**Criterios de aceptación**

- [x] Registro de pruebas unitarias desarrolladas, junto con los resultados obtenidos.

**Material de apoyo:**

Revisar esta [plantilla](https://docs.google.com/document/d/1Uuk4IQHjhwm-3rQWwsmZQ5uts6X3SCEJ8OpJEsvUHXU/edit?usp=sharing) como guía para el desarrollo de pruebas unitarias.

**Comment by criss201x** [comment]
Se realizan pruebas unitarias en el gestor_documental_mid con el fin de automatizar las pruebas sobre cada componente del api a manera individual, para dicho fin se escogió el modulo integrado unittest en Python el cual es compatible con los módulos y la arquitectura del api. para implementar las pruebas unitarias en el gestor documental mid se realizaron los siguientes pasos:

1. Usar la rama [test](https://github.com/udistrital/gestor_documental_mid/tree/test) o definirla si no existe, con el fin de realizar estas pruebas sin perjudicar lo que se encuentra desplegado en ambiente de pruebas o producción 
2. Crear un archivo bajo el prefijo o sufijo test_*.py donde el nombre del archivo debe empezar o terminar con 'test' para estas pruebas el archivo se define como [test_api.py](https://github.com/udistrital/gestor_documental_mid/blob/test/test_api.py), este archivo contiene todo el código necesario para ejecutar las pruebas sin alterar el código original del api
3. Dentro del archivo mencionado anteriormente se deben importar las siguientes librerías, ademas se debe definir una clase la cual herede los objetos necesarios del modulo unittest para las pruebas
![Captura de pantalla de 2021-09-30 13-32-59](https://user-images.githubusercontent.com/57843585/135511453-1db0ede9-9284-4327-b891-4391c990dabc.png)
4. La clase definida en la imagen anterior deberá contener todos los métodos y atributos necesarios para realizar las pruebas ya que las pruebas realizadas en unittest se programan en un enfoque orientado a objetos, a continuación se relacionan los atributos necesarios que servirán como datos de entrada para las pruebas
![Captura de pantalla de 2021-09-30 15-09-34](https://user-images.githubusercontent.com/57843585/135523962-84778aa1-96c3-44ba-8e91-13b6fb33035c.png)
5. Definir métodos de prueba unitaria, es decir que cada prueba unitaria sobre un componente del api sera un método, cada uno de ellos viene como un bloque dividido en el código necesario para hacer la prueba y las sentencias de prueba definida como 'assertEqual' las cuales devuelven un mensaje de éxito o fracaso dependiendo del desempeño de la prueba, a continuación se adjuntan dos ejemplos en el gestor_documental_mid
![Captura de pantalla de 2021-09-30 15-47-52](https://user-images.githubusercontent.com/57843585/135527926-9f0f4c9f-f7b2-4708-becb-d47bcab0dca2.png)
los métodos de prueba para el gestor documental mid son los siguientes 
![Captura de pantalla de 2021-09-30 15-52-41](https://user-images.githubusercontent.com/57843585/135528609-179ba59b-6563-4930-ac9c-30dbb2140e72.png)
6. Definir variables de entorno en el sistema referentes a los apis que consume el gestor documental mid, el puerto, y el usuario autenticado en nuxeo, de la siguiente manera 
    - FLASK_ENV=DEVELOPMENT o TEST
    - API_PORT=8080
    - NUXEO_URL=https://dominio/nuxeo/
    - NUXEO_USERNAME=tu_usuario
    - NUXEO_PASSWORD=tu_contraseña
    - DOCUMENTOS_CRUD_URL=http://dominio/v1
7. Compilar el api, las variables de entorno deben estar previamente 'seteadas' en el sistema operativo donde se va compilar, posterior a ello para este caso el api se compila de la siguiente manera 
![Captura de pantalla de 2021-09-30 16-32-17](https://user-images.githubusercontent.com/57843585/135533104-f263a665-3c1f-42c7-937a-3164fe22c81e.png)
así el api entra en ejecución para ambiente de pruebas, donde este esta a la escucha de peticiones http
8. Deberá abrir una nueva pestaña para el shell que esta usando o abrir un segundo shell donde va a compilar el archivo de pruebas unitarias, para ello debe activar el ambiente de desarrollo python y se sugiere también 'setear' las variables de entorno, puede compilar las pruebas unitarias de dos maneras, la primera es ejecutar simplemente el script de la siguiente manera 
![Captura de pantalla de 2021-09-30 17-02-03](https://user-images.githubusercontent.com/57843585/135536006-c7dd1a99-4093-4245-94e0-e9d58c7bf5c4.png)
obteniendo como resultado los logs de los test que fueron exitosos, otra manera de compilar el api en modo test es con el comando python3 -m unittest, allí se verán logs mas detallados incluyendo información de los test fallidos dentro de la compilación  
![Captura de pantalla de 2021-09-30 17-22-01](https://user-images.githubusercontent.com/57843585/135538055-3ea74231-1145-4130-bf83-8d2126e7a16f.png)
las pruebas fallidas pertenecen a situaciones donde normalmente el api fallaría como por ejemplo una caída del servidor o un error 401, se podría invertir el proceso de modo que solo se quiera hacer pruebas sobre el api en condiciones de falla para ver como responde pero los test de uso normal fallarían.

**Comment by a52290451** [comment]
Se validan pruebas unitarias realizadas por el desarrollador.
