### ISSUE TITLE
Consumo de API gestor_documental_mid en cumplidos.

### ISSUE THREAD

**Issue by a52290451** [udistrital/gestor_documental_mid#23]
Realizar conexión con el API gestor_documental_mid y alterar el flujo que actualmente se maneja para almacenar y autenticar documentos en nuxeo, así como consultarlos posteriormente.

**Criterios de aceptación**

- [x] commit en rama feature con los cambios realizados.
- [x] Pruebas funcionales.

**Comment by JuanCamiloMartinezLopez** [comment]
### IMPLEMENTACIÓN DEL GESTOR DOCUMENTAL EN CUMPLIDOS
para la realización de las [pruebas funcionales](https://github.com/udistrital/gestor_documental_mid/issues/10) del gestor documental se decide implementar inicial de forma parcial en el sistema de cumplidos, para esto se crea una [rama](https://github.com/udistrital/cumplidos_cliente/tree/feature/IntegracionSistemaGestionDocumental) donde se integraron los cambios.

**Comment by a52290451** [comment]
Faltan realizar pruebas funcionales  y su implementación en los demás módulos del sistema.
