### ISSUE TITLE
Consumo de API gestor_documental_mid en PÓLUX

### ISSUE THREAD

**Issue by a52290451** [udistrital/gestor_documental_mid#24]
Realizar conexión con el API gestor_documental_mid y alterar el flujo que actualmente se maneja para almacenar y autenticar documentos en nuxeo, así como consultarlos posteriormente.

**Criterios de aceptación**

- [x] commit en rama feature con los cambios realizados.
- [x] Pruebas funcionales (Desarrollador).

**Comment by mantnicot** [comment]
Se realiza la apropiacion del nuevo api de gestion de documento, por medio del manual proposionado 

Se comienza la implementacion en POLUX


[Manual general  gestor documental mid ](https://docs.google.com/document/d/1ETG2KtDpNXN8hTyjDIe-VkVJ9gGFqzaC/edit)

**Comment by mantnicot** [comment]
[Pruebas funcionales Gestor documental.xlsx](https://github.com/udistrital/gestor_documental_mid/files/7781420/Pruebas.funcionales.Gestor.documental.xlsx)

Se realizan las pruebas para poder cargar , actualizar  y visualizar documentos

**Comment by a52290451** [comment]
Se validan pruebas funcionales realizadas.

**Comment by mantnicot** [comment]
Se agrega nuevo documento de prueba para documentos grandes por medio del gestor documental

[Documento](https://1drv.ms/w/s!AkQEWBEvYVTDiFUUp2zZxu3l9fxS?e=RUgNO4)
