### ISSUE TITLE
Corrección de errores en el código del gestor_documental_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/gestor_documental_mid#6]
Realizar la corrección de errores encontrados en el API "gestor_documental_mid".

**Criterio de aceptación**:

- [x] Commit en rama Feature con cambios realizados.

**Nota:** tomar en consideración la investigación realizada en [ISSUE #5](https://github.com/udistrital/gestor_documental_mid/issues/5).

**Comment by criss201x** [comment]
Se agrega validación de nombres de archivos repetidos en Nuxeo, se debe evaluar si este feature se hace a nivel general o solo a nivel de workspace en Nuxeo, se adjunta ejemplo de petición.

-![image](https://user-images.githubusercontent.com/57843585/131927653-014708ee-a867-4e95-b0f4-426fb89b2eb7.png)

**Comment by criss201x** [comment]
Se logra garantizar integridad y no repudio del documento subido a Nuxeo por medio de funciones de cifrado asimétrico dentro del MID, esto genera una par de llaves publicas y privadas  las cuales se deben almacenar para la posterior validación del documento, inicialmente se propuso en la mesa de trabajo_3 almacenar estas claves cifradas en base64 en la [columna metadatos de la tabla documentos en la base de datos de DOCUMENTOS_CRUD](https://github.com/udistrital/documentos_crud/blob/e09fe25bf8a947c1f7937934bf12c8fff5b9e27b/models/documento.go#L18).

- los datos los datos de la firma electrónica son los siguientes: 
![Captura de pantalla de 2021-09-13 17-21-46](https://user-images.githubusercontent.com/57843585/133164110-e103bc5a-1be9-4ed1-8527-fbe3cd92d7e5.png)

- Ejemplo de respuesta en petición post cuando se sube un documento a Nuxeo
![Captura de pantalla de 2021-09-13 17-29-23](https://user-images.githubusercontent.com/57843585/133164843-c5ccbdb2-575d-4590-9a56-36c778625814.png)

**Comment by criss201x** [comment]
Se propone función de validación del documento para una posterior implementacion, aunque en la mesa de trabajo_3 se definió que el modulo de validación de un documento es un desarrollo independiente el cual tendrá sus propios requerimientos, se propone una función la cual puede ser integrada en un endpoint de este mismo MID de la siguiente manera:
![Captura de pantalla de 2021-09-13 17-58-41](https://user-images.githubusercontent.com/57843585/133167724-8f243cda-e740-4141-ae1e-231deff9ccab.png)
