### ISSUE TITLE
Integración del servicio gestor_documental_mid en el cliente de novedades

### ISSUE THREAD

**Issue by a52290451** [udistrital/gestor_documental_mid#7]
Realizar la integración del API gestor_documental_mid con el sistema Novedades para almacenar, autenticar y consultar documentos en NUXEO.

**criterio de aceptación**

- [x] Commit en rama Feature con los cambios realizados.

**Comment by a52290451** [comment]
Registrar integración del API con el cliente de Novedades.

**Comment by criss201x** [comment]
Se creo una rama para la integración del gestor documental mid en el cliente de novedades: https://github.com/udistrital/novedades_cliente/tree/feature/integracionGestorDoc , queda pendiente confirmar con @ricardoavendano que todas las funcionalidades del gestor documental mid funcionan correctamente en dicho cliente.
