### ISSUE TITLE
Integración swagger

### ISSUE THREAD

**Issue by a52290451** [udistrital/gestor_documental_mid#8]
Realizar la integración Swagger del API gestor_documental_mid.

**Criterio de aceptación**

- [x] Commit en rama feature con cambios realizados.

**Comment by criss201x** [comment]
Se sugiere cambiar la librería [flask-restful](https://flask-restful.readthedocs.io/en/latest/) por [flask-restx](https://flask-restx.readthedocs.io/en/latest/quickstart.html) debido a falta de herramientas para la generación de la documentación open api (swagger).

**Comment by criss201x** [comment]
Endpoints del gestor documental mid en open api 
![Captura de pantalla de 2021-09-16 13-24-03](https://user-images.githubusercontent.com/57843585/133665045-ea8c2cf4-acc8-4aec-8656-c6ddb9d88c9f.png)

**Comment by criss201x** [comment]
Se realizan pruebas sobre los endpoints definitivos del mid 

- **Nuxeo_healtcheck**: valida el estado del gestor documental Nuxeo el endpoint es http://endpoint:8080/v1/
![Captura de pantalla de 2021-09-20 12-37-45](https://user-images.githubusercontent.com/57843585/134048366-d5ab3b44-efec-4f89-b896-769090a6a01b.png)

- **document/upload**: sube un documento al gestor documental Nuxeo los datos del cuerpo de la petición son los siguientes 
[{IdDocumento, nombre, file }] donde el id corresponde al tipo de documento, el nombre define como se va a guardar el archivo en nuxeo y file es el pdf en base_64
![Captura de pantalla de 2021-09-20 12-53-34](https://user-images.githubusercontent.com/57843585/134050462-a1ffc064-1e00-4895-9e76-706d789b3fa5.png)

- **document/uid** : permite consultar un documento por su uid en el gestor documental Nuxeo 
![Captura de pantalla de 2021-09-20 12-59-47](https://user-images.githubusercontent.com/57843585/134051332-e014793a-fc06-435e-999c-716d570b41d4.png)

- **document/uid/metadata**: permite agregar metadatos aun documento subido en el gestor documental Nuxeo, los metadatos se deben agregar de la siguiente forma 
![Captura de pantalla de 2021-09-20 13-03-16](https://user-images.githubusercontent.com/57843585/134051677-f1db8964-c01a-4753-8289-4cb8eac0e831.png)

y la respuesta debería verse de la siguiente manera  
![Captura de pantalla de 2021-09-20 13-04-32](https://user-images.githubusercontent.com/57843585/134051869-93d50ae8-195c-463f-887e-2f5a1cf045b6.png)

**Comment by criss201x** [comment]
Se agrega nuevo endpoint para eliminar documentos existentes en Nuxeo por su UID 
![Captura de pantalla de 2021-09-23 16-54-29](https://user-images.githubusercontent.com/57843585/134589368-383e6ac9-d180-490d-964a-8239daf73f03.png)
