### ISSUE TITLE
Documentación y manual de servicio para API gestor_documental_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/gestor_documental_mid#9]
Documentar el desarrollo realizado en el API gestor_documental_mid, así como la creación del manual de servicio correspondiente.

**Criterios de aceptación**

- [x] Documentación del API.
- [x] Manual de servicio.

**Comment by criss201x** [comment]
Se adjuntan links de las grabaciones de las 4 mesas de trabajo realizadas referentes a los avances en desarrollo del gestor documental

- [Mesa de trabajo 1](https://drive.google.com/file/d/1ps_emJ_cxyQE1KNTMn3syCjpS2p0Dxi3/view)
- [Mesa de trabajo 2](https://drive.google.com/file/d/1e4u-Ny6qadw6KXsoyWLh8A7xwOytlvJz/view)
- [Mesa de trabajo 3](https://drive.google.com/file/d/1McbZk_cNTpgnKQ3fOc1g6HnyUuF3bl0j/view)
- [Mesa de trabajo 4](https://drive.google.com/file/d/1yMnR3scWI00FLFGXbhBztg_yR16MT9Y_/view)

**Comment by criss201x** [comment]
Se adjunta primera versión del informe y manual de usuario del gestor documental mid

- [Enlace del Informe gestor documental mid version 1.0](https://docs.google.com/document/d/1ETG2KtDpNXN8hTyjDIe-VkVJ9gGFqzaC/edit?usp=sharing&ouid=110288693142592643207&rtpof=true&sd=true)
